version: 2.1

build_py3_gpu_template: &build_py3_gpu_template
  working_directory: /workspace
  docker:
    - image: docker:git
  steps:
    - checkout

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - run:
        name: "Building NVTX-Plugins Test Container"

        command: |
          export CACHE_DIR="/workspace/build_cache"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          mkdir -p "${CACHE_DIR}/${TENSORFLOW_CONTAINER_TAG}"
          docker build -t "nvtx_container" \
            --build-arg TF_CONTAINER_VERSION="${TENSORFLOW_CONTAINER_TAG}" \
            --build-arg GIT_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" \
            --build-arg GIT_COMMIT_SHA1="${CIRCLE_SHA1}" \
             - < .circleci/Dockerfile
          docker save "nvtx_container" | gzip > "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"

        persist_to_workspace:
          root: /workspace/build_cache
          paths: ${CONTAINER_SAVE_RELPATH}


test_tensorflow_session_template: &test_tensorflow_session_template
  working_directory: ~/build
  docker:
    - image: docker:git
  steps:
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /workspace/build_cache

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - run:
        name: TEST RUN - Tensorflow Session API
        command: |
          export CACHE_DIR="/workspace/build_cache"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          docker load -i "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"
          docker run --rm --workdir /dist/nvtx-plugins "nvtx_container" bash -c "python examples/tf_session_example.py"


test_keras_template: &test_keras_template
  working_directory: ~/build
  docker:
    - image: docker:git
  steps:
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /workspace/build_cache

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - run:
        name: TEST RUN - Tensorflow Session API
        command: |
          export CACHE_DIR="/workspace/build_cache"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          docker load -i "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"
          docker run --rm --workdir /dist/nvtx-plugins "nvtx_container" bash -c "python examples/keras_example.py"


jobs:

  # =================================================== #
  #             Building Base Images for Test           #
  # =================================================== #

  build_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
    <<: *build_py3_gpu_template

  build_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
    <<: *build_py3_gpu_template

  # =================================================== #
  #            Running Tensorflow Session Test          #
  # =================================================== #

  test_tensorflow_session_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
    <<: *test_tensorflow_session_template

  test_tensorflow_session_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
    <<: *test_tensorflow_session_template

  # =================================================== #
  #                Running Keras API Test               #
  # =================================================== #

  test_keras_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
    <<: *test_keras_template

  test_keras_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
    <<: *test_keras_template

###################################################################################
#                               CircleCI WORKFLOWS                                #
###################################################################################

workflows:
  version: 2
  build-and-test:
    jobs:

      ############################################################
      #           Jobs for Tensorflow Latest Container           #
      ############################################################

      - build_latest_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - test_tensorflow_session_latest_py3_gpu:
          requires:
            - build_latest_py3_gpu

      - test_keras_latest_py3_gpu:
          requires:
            - build_latest_py3_gpu

      ############################################################
      #           Jobs for Tensorflow Nightly Container           #
      ############################################################

      - build_nightly_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - test_tensorflow_session_nightly_py3_gpu:
          requires:
            - build_nightly_py3_gpu

      - test_keras_nightly_py3_gpu:
          requires:
            - build_nightly_py3_gpu

      # - test_nightly_py3_gpu:
      #     filters:
      #       tags:
      #         only: /\d+\.\d+(\.\d+)?(\S*)?$/
      #       branches:
      #         ignore: /.*/
