version: 2.1

jobs:

  test_nightly_py3_gpu:
    working_directory: ~/build
    docker:
      - image: docker:git
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: true

      - run:
          name: TEST BUILD - Build Docker Image Python 3 Tensorflow Nightly GPU
          command: |
            docker build -t nvtx_container --build-arg TF_CONTAINER_VERSION="nightly-gpu-py3" --build-arg GIT_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" --build-arg GIT_COMMIT_SHA1="${CIRCLE_SHA1}" - < .circleci/Dockerfile
            docker run --rm -v "$(pwd):/workspace" --workdir /workspace nvtx_container bash -c "python examples/keras_example.py"
            docker run --rm -v "$(pwd):/workspace" --workdir /workspace nvtx_container bash -c "python examples/tf_session_example.py"

  test_latest_py3_gpu:
    working_directory: ~/build
    docker:
      - image: docker:git
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: true

      - run:
          name: TEST BUILD - Build Docker Image Python 3 Tensorflow Latest GPU
          command: |
            docker build -t nvtx_container --build-arg TF_CONTAINER_VERSION="latest-gpu-py3" --build-arg GIT_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" --build-arg GIT_COMMIT_SHA1="${CIRCLE_SHA1}" - < .circleci/Dockerfile
            docker run --rm -v "$(pwd):/workspace" --workdir /workspace nvtx_container bash -c "python examples/keras_example.py"
            docker run --rm -v "$(pwd):/workspace" --workdir /workspace nvtx_container bash -c "python examples/tf_session_example.py"

###################################################################################
#                               CircleCI WORKFLOWS                                #
###################################################################################

workflows:
  version: 2
  build-and-deploy:
    jobs:

      ###################################################################################
      #  TEST BUILDS with TensorLayer installed from Source - NOT PUSHED TO DOCKER HUB  #
      ###################################################################################

      - test_nightly_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - test_latest_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      # - test_nightly_py3_gpu:
      #     filters:
      #       tags:
      #         only: /\d+\.\d+(\.\d+)?(\S*)?$/
      #       branches:
      #         ignore: /.*/
