version: 2.1

build_py3_gpu_template: &build_py3_gpu_template

  working_directory: /workspace

  docker:
    - image: docker:git

  steps:

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - checkout

    - run:
        name: "Building NVTX-Plugins Test Container"

        command: |
          export CACHE_DIR="/workspace/build_cache"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          mkdir -p "${CACHE_DIR}/${TENSORFLOW_CONTAINER_TAG}"
          docker build -t "nvtx_container" \
            --build-arg TF_CONTAINER_VERSION="${TENSORFLOW_CONTAINER_TAG}" \
            --build-arg GIT_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" \
            --build-arg GIT_COMMIT_SHA1="${CIRCLE_SHA1}" \
             - < .circleci/Dockerfile
          printf "\nSaving  docker image to disk... Please wait\n\n"
          docker save "nvtx_container" | gzip > "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"
          printf "\nFinished with Success !\n\n"

    - persist_to_workspace:
      root: /workspace
      paths: build_cache/*


test_example_template: &test_example_template

  working_directory: ~/build

  docker:
    - image: docker:git

  steps:

    - setup_remote_docker:
      reusable: true
      exclusive: true

    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /workspace/build_cache

    - run:
        name: TEST RUN - Tensorflow Session API
        command: |
          export CACHE_DIR="/workspace/build_cache"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          ls -al ${CACHE_DIR}
          printf "\nLoading previously built docker image... Please wait\n\n"
          docker load -i "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"
          printf "\nRunning Unittest ... Please Wait\n\n"
          docker run --rm --workdir /dist/nvtx-plugins "nvtx_container" bash -c "python examples/${PYTHON_EXAMPLE_FILE}"
          printf "\nFinished with Success !\n\n"


jobs:

  # =================================================== #
  #             Building Base Images for Test           #
  # =================================================== #

  build_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
    <<: *build_py3_gpu_template

  build_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
    <<: *build_py3_gpu_template

  # =================================================== #
  #            Running Tensorflow Session Test          #
  # =================================================== #

  test_tensorflow_session_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
      PYTHON_EXAMPLE_FILE: "tf_session_example.py"
    <<: *test_example_template

  test_tensorflow_session_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
      PYTHON_EXAMPLE_FILE: "tf_session_example.py"
    <<: *test_example_template

  # =================================================== #
  #                Running Keras API Test               #
  # =================================================== #

  test_keras_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
      PYTHON_EXAMPLE_FILE: "keras_example.py"
    <<: *test_example_template

  test_keras_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
      PYTHON_EXAMPLE_FILE: "keras_example.py"
    <<: *test_example_template

###################################################################################
#                               CircleCI WORKFLOWS                                #
###################################################################################

workflows:
  version: 2
  build-and-test:
    jobs:

      ############################################################
      #           Jobs for Tensorflow Latest Container           #
      ############################################################

      - build_latest_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - test_tensorflow_session_latest_py3_gpu:
          requires:
            - build_latest_py3_gpu

      - test_keras_latest_py3_gpu:
          requires:
            - build_latest_py3_gpu

      ############################################################
      #           Jobs for Tensorflow Nightly Container           #
      ############################################################

      - build_nightly_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - test_tensorflow_session_nightly_py3_gpu:
          requires:
            - build_nightly_py3_gpu

      - test_keras_nightly_py3_gpu:
          requires:
            - build_nightly_py3_gpu

      # - test_nightly_py3_gpu:
      #     filters:
      #       tags:
      #         only: /\d+\.\d+(\.\d+)?(\S*)?$/
      #       branches:
      #         ignore: /.*/
