version: 2.1

build_py3_gpu_template: &build_py3_gpu_template
  working_directory: /workspace
  docker:
    - image: docker:git
  steps:
    - checkout

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - run:
        name: "Building NVTX-Plugins Test Container"

        command: |
          export CACHE_DIR="/workspace/build_cache/"
          export CONTAINER_SAVE_RELPATH="${TENSORFLOW_CONTAINER_TAG}/nvtx_container.tar.gz"
          mkdir -p ${CACHE_DIR}
          docker build -t "nvtx_container" \
            --build-arg TF_CONTAINER_VERSION="${TENSORFLOW_CONTAINER_TAG}" \
            --build-arg GIT_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" \
            --build-arg GIT_COMMIT_SHA1="${CIRCLE_SHA1}" \
             - < .circleci/Dockerfile
          docker save "nvtx_container" | gzip > "${CACHE_DIR}/${CONTAINER_SAVE_RELPATH}"

        persist_to_workspace:
          root: /workspace/build_cache
          paths: ${CONTAINER_SAVE_RELPATH}


test_tensorflow_session_template: &test_tensorflow_session_template
  working_directory: ~/build
  docker:
    - image: docker:git
  steps:
    - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /workspace

    - setup_remote_docker:
        reusable: true
        exclusive: true

    - run:
        name: TEST RUN - Tensorflow Session API
        command: |
          docker load -i /persistant_workspace/nvtx_container.tar
          docker run --rm --workdir /dist/nvtx-plugins "nvtx_container:${CIRCLE_WORKFLOW_JOB_ID}" bash -c "python examples/tf_session_example.py"



jobs:
  build_latest_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "latest-gpu-py3"
    <<: *build_py3_gpu_template

  build_nightly_py3_gpu:
    environment:
      TENSORFLOW_CONTAINER_TAG: "nightly-gpu-py3"
    <<: *build_py3_gpu_template

  # test_tensorflow_session:
  #   working_directory: ~/build
  #   docker:
  #     - image: docker:git
  #   steps:
  #     - checkout
  #
  #     - setup_remote_docker:
  #         reusable: true
  #         exclusive: true
  #
  #     - run:
  #         name: TEST RUN - Tensorflow Session API
  #         command: |
  #           docker run --rm --workdir /dist/nvtx-plugins "nvtx_container:${CIRCLE_WORKFLOW_JOB_ID}" bash -c "python examples/tf_session_example.py"
  #
  # test_keras:
  #   working_directory: ~/build
  #   docker:
  #     - image: docker:git
  #   steps:
  #     - checkout
  #
  #     - setup_remote_docker:
  #         reusable: true
  #         exclusive: true
  #
  #     - run:
  #         name: TEST RUN - Keras API
  #         command: |
  #           docker run --rm --workdir /dist/nvtx-plugins "nvtx_container:${CIRCLE_WORKFLOW_JOB_ID}" bash -c "python examples/keras_example.py"

###################################################################################
#                               CircleCI WORKFLOWS                                #
###################################################################################

workflows:
  version: 2
  build-and-test:
    jobs:

      ###################################################################################
      #  TEST BUILDS with TensorLayer installed from Source - NOT PUSHED TO DOCKER HUB  #
      ###################################################################################

      - build_latest_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      - build_nightly_py3_gpu:
          filters:
            tags:
              ignore: /.*/
            # branches:
            #   ignore: master

      # - test_nightly_py3_gpu:
      #     filters:
      #       tags:
      #         only: /\d+\.\d+(\.\d+)?(\S*)?$/
      #       branches:
      #         ignore: /.*/
